### ISSUE TITLE
Janky circular progress indicator

### ISSUE THREAD

**Issue by dpinn** [aforemny/elm-mdc#308] opened 2020-08-12 03:02 UTC
![image](https://user-images.githubusercontent.com/724936/89970363-08de0b80-dc9c-11ea-90cd-ee11bb4ed3a3.png)

There's an MP4 video file in the attached zip. 

[progress.zip](https://github.com/aforemny/elm-mdc/files/5060369/progress.zip)

**Comment by berenddeboer** [comment] 2020-08-13 02:53
Ah, I've seen that too when upgrading an app. I just merged the fix I had pending. So get the latest, that should fix it. The issue is that you have a text-align center on a parent.

**Closed by berenddeboer** 2020-08-13 02:53 UTC
