### ISSUE TITLE
Choice chip background highlight does not turn off when selecting a new chip

### ISSUE THREAD

**Issue by mkreisel** [aforemny/elm-mdc#221] opened 2019-06-10 01:57 UTC
When a chip is selected, the background becomes highlighted. This background highlight should fade when another click happens on the page. However this does not happen, and chip backgrounds can remain highlighted as other chips are selected. Below is a gif illustrating the problem taken from the elm-mdc demo running on Chrome Version 75.0.3770.80 (Official Build) (64-bit) on Ubuntu 18.04.

![mdc_chip_bug](https://user-images.githubusercontent.com/7807896/59167950-9f93c300-8b01-11e9-838b-7919a6038972.gif)

**Comment by aforemny** [comment] 2019-06-16 09:23
As with #220 I cannot reproduce the observed behavior in Chrome Version 75.0.3770.80 (64-bit) on Linux. Let's figure out #220 first, since I think both issues are of the same underlying problem.

**Comment by SidneyNemzer** [comment] 2019-06-17 17:26
Similarly to #219, I can reproduce this by 'tapping' my laptop's trackpad rather than 'clicking'.

**Comment by aforemny** [comment] 2019-07-02 19:19
I am closing this because I am assuming this has been fixed in #219. If the issue persists, please re-open. Thank you both for the report and assistance in solving this!

**Closed by aforemny** 2019-07-02 19:19 UTC
